export enum MonacoEditorLanguages {
    JavaScript = "javascript",
    TypeScript = "typescript",
    HTML = "html",
    CSS = "css",
    JSON = "json",
    Python = "python",
    Java = "java",
    Go = "go",
    Cpp = "cpp",
    CSharp = "csharp",
    PHP = "php",
    Ruby = "ruby",
    SQL = "sql",
    Markdown = "markdown",
    Lua = "lua",
    Dart = "dart",
    Swift = "swift",
    ObjectiveC = "objective-c",
    R = "r",
    Shell = "shell"
}
